variable "function_role_name" {}
variable "function_policy_name" {}
variable "function_name" {}
variable "memory_size" {}
variable "image_uri" {}
variable "timeout" {}
variable "ephemeral_storage_size" {}
variable "log_format" {}
variable "cost_metrics_value" {}
variable "log_retention_in_days" {}
variable "dynamodb_table_name" {}